version: '3'

services:
  app:
    build: .
    container_name: advrestapi
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev